export const ErrorCodes = {
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_ALREADY_EXISTS: 'PRODUCT_ALREADY_EXISTS',
    ARTIST_NOT_FOUND: 'ARTIST_NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    STORAGE_ERROR: 'STORAGE_ERROR',
} as const;
